spring:
  profiles:
    active: dev
---
#开发环境
spring:
  profiles: dev
  datasource:  #配置连接数据库的基本信息 username password url driver
    username: root
    password: 20peng
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&characterEncoding=utf-8&generateSimpleParameterMetadata=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false #关闭thymeleaf模板的缓存
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#配置mybatis
mybatis:
  type-aliases-package: com.pjj.entity #配置类名简写
  mapper-locations: classpath:mybatis/mapper/*.xml #加载mapper.xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印日志
    map-underscore-to-camel-case: true #开始驼峰映射

#配置日志
logging:
  level:
    root: info #全部日志级别为 info
    com.pjj: debug #该包下的日志级别为 debug
  file:
    name: log/blog.log #将日志储存到 项目/log/blog.log中

comment:
  avatar: /images/avatar.jpg

---
#生产环境
server:
  port: 80
spring:
  profiles: pro
  datasource:
    username: root
    password: 20peng
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&generateSimpleParameterMetadata=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.pjj.entity
  mapper-locations: classpath:mybatis/mapper/*.xml #加载mapper.xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志
logging:
  level:
    root: warn
    com.pjj: info
  file:
    name: log/blog.log

comment:
  avatar: /images/avatar.jpg
